# Generated by Django 5.2.3 on 2025-06-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('automaton_type', models.CharField(choices=[('DFA', 'Déterministe'), ('NFA', 'Non Déterministe'), ('ε-NFA', 'Epsilon-NFA')], default='DFA', max_length=10)),
                ('alphabet', models.JSONField(default=list)),
                ('states', models.JSONField(default=list)),
                ('initial_state', models.CharField(max_length=50)),
                ('final_states', models.JSONField(default=list)),
                ('transitions', models.JSONField(default=dict)),
                ('is_deterministic', models.BooleanField(default=False)),
            ],
        ),
    ]
