# Generated by Django 5.2.3 on 2025-06-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_automate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automate',
            name='is_deterministic',
            field=models.BooleanField(default=True),
        ),
    ]
